### ISSUE TITLE
Submission Screen – Color Picker

### ISSUE THREAD

**Issue by lukepighetti** [lukepighetti/pocketbase_flutter_app#11]
Add a color picker to the Submission Screen,
Default to dominant color from the first image that is picked

<img width="662" alt="Screen Shot 2022-09-19 at 6 24 31 PM" src="https://user-images.githubusercontent.com/666539/191130137-f64659d3-67ee-4fa7-b477-8b05380de607.png">

https://excalidraw.com/#json=ExXohIFhPAl45bBd1LpGp,ljt8Wg1Iw8uiguwx4mrBHA

**Comment by Lootwig** [comment]
Man, _Someone_ really needs to work on this....

**Comment by Lootwig** [comment]
@lukepighetti what "background" is supposed to be set? the app background that is currently white?

**Comment by lukepighetti** [comment]
Yes, the scaffold background
